name: Jest Testing

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]  # specify the Node.js versions you want to test against
    env:
      YARN_IGNORE_ENGINES: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn ci:test

      - name: Main Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Main Test Report (${{ matrix.node-version }})
          path: reports/main/jest-*.xml
          reporter: jest-junit
          list-tests: 'failed'

      - name: Renderer Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Renderer Test Report (${{ matrix.node-version }})
          path: reports/renderer/jest-*.xml
          reporter: jest-junit
          list-tests: 'failed'

      - name: Preload Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Preload Test Report (${{ matrix.node-version }})
          path: reports/preload/jest-*.xml
          reporter: jest-junit
          list-tests: 'failed'
